### ISSUE TITLE
Stemmer command line usage in version 2.0

### ISSUE THREAD

**Issue by Harry27PL** [morfologik/morfologik-stemming#81]
I don't know Java. I found that in previous version I can run stemmer by command:

    echo "chrząszcz brzmi w trzcinie w Szczebrzeszynie" | java -jar morfologik-tools-1.10.0-standalone.jar plstem 

What is the equivalent command for version 2.0?

**Comment by dweiss** [comment]
Redirect to a file and read from that. There is no equivalent -- the support for input streams have been removed because there is no way to properly detect input encoding from command line (now all the input files have to be in UTF8).

If you need command-line support then you can write it easily based on the API (and using the 'default' encoding Java gives you), but the support for it won't come back to command line tools.
